[package]
name = "udbg"
version = "0.1.0"
authors = ["metaworm <metaworm@outlook.com>"]
edition = "2018"

[features]
dbglog = []

[build-dependencies]
cc = '1.0'

[dependencies]
cfg-if = '1.0'
glob = '0.3'
hex = '0.4'
log = '0.4'
spin = '0.9'
ctor = '0.1'
regex = '1.4'
pdb = '0.7'
extend = '1.1'
bitflags = '1.2'
anyhow = '1.0'
futures = '0.3'
thiserror = '1.0'
crossbeam = '0.8'
parking_lot = '0.12'
serde-value = '0.7'
derive_more = '0.99'
goblin = {version = '0.5'}
memmap = {version = '0.7.0'}
cpp_demangle = {version = '0.3'}
guid = {version = '0.2', package = 'guid-create'}
serde = {version = "1.0", default-features = false, features = ['derive', 'rc', 'alloc']}
iced-x86 = {version = '1.11', default-features = false, features = ['decoder', 'intel', 'no_std']}
cstrptr = {git = 'https://github.com/metaworm/cstrptr-rs', default-features = false, features = ['alloc']}

[target.'cfg(windows)'.dependencies]
winapi = {version = '0.3.9', features = [
    "winnt", "processthreadsapi", "psapi", "errhandlingapi", "winuser", "winbase", "fileapi",
    "memoryapi", "dbghelp", "debugapi", "ioapiset", "winerror", "stringapiset", "winnls",
    "shellapi", "winsvc", "synchapi", "wincrypt", 'softpub',
    "shellscalingapi", "sysinfoapi", "heapapi", 'tlhelp32', 'wow64apiset', "securitybaseapi"
]}
ntapi = '0.3'
unicase = '2.6'
msvc-demangler = {git = 'https://github.com/mstange/msvc-demangler-rust'}

[target.'cfg(not(windows))'.dependencies]
nix = '0.23'
libc = '^0.2'
text_io = '0.1.8'

[target.'cfg(target_os="macos")'.dependencies]
mach = '0.3'
libproc = '0.10'

[dev-dependencies]
regex = '1.5'
structopt = '0.3.8'
flexi_logger = '0.22'