[package]
name = "udbg-base"
version = "0.1.0"
authors = ["metaworm <metaworm@outlook.com>"]
edition = "2018"

[features]
default = ['udbg']
udbg = []
dbglog = []
csutil = ['capstone']

[build-dependencies]
cc = '1.0'

[dependencies]
cfg-if = '1.0'
chrono = '0.4'
glob = '0.3'
log = '0.4'
spin = '^0.7'
ctor = '^0.1'
regex = '1.4'
bitflags = '^1.2'
anyhow = '1.0'
futures = '0.3'
thiserror = '1.0'
crossbeam = '0.8'
parking_lot = '0.11'
serde-value = '0.7'
derive_more = '0.99'
goblin = {version = '0.2.0'}
memmap = {version = '0.7.0'}
encoding = {version = '0.2.3'}
cpp_demangle = {version = '0.3'}
capstone = {version = '0.10', optional = true}
# llua = {git = 'https://github.com/udbg/llua', optional = true}
serde = {version = "1.0", default-features = false, features = ['derive', 'rc', 'alloc']}
iced-x86 = {version = '1.11', default-features = false, features = ['decoder', 'intel', 'no_std']}
cstrptr = {git = 'https://github.com/metaworm/cstrptr-rs', default-features = false, features = ['alloc']}

[target.'cfg(windows)'.dependencies]
winapi = {version = '0.3.9', features = [
    "winnt", "processthreadsapi", "psapi", "errhandlingapi", "winuser", "winbase", "fileapi",
    "memoryapi", "dbghelp", "debugapi", "ioapiset", "winerror", "stringapiset", "winnls",
    "shellapi", "winsvc", "synchapi", "wincrypt", 'softpub',
    "shellscalingapi", "sysinfoapi", "heapapi", 'tlhelp32', 'wow64apiset', "securitybaseapi"
]}
pdb = '0.7'
ntapi = '0.3'
unicase = '2.6'
msvc-demangler = {git = 'https://github.com/mstange/msvc-demangler-rust'}

[target.'cfg(not(windows))'.dependencies]
nix = '^0.20'
libc = '^0.2'
errno = '0.2.4'
text_io = '0.1.8'

[dev-dependencies]
regex = '1.5'
structopt = '0.3.8'
flexi_logger = '0.22'